services:

    chargify.site_handler:
        class: Litwicki\Bundle\ChargifyBundle\Handler\ChargifySiteHandler
        arguments:
            - "%chargify.domain%"
            - "%chargify.api_id%"
            - "%chargify.api_secret%"
            - "%chargify.api_password%"
            - "%chargify.api_key%"
            - "%chargify.shared_key%"
            - "%chargify.data_format%"
            - "%chargify.test_mode%"
            - "@serializer"

    chargify.entity.handler:
        class: Litwicki\Bundle\ChargifyBundle\Model\Handler\ChargifyEntityHandler
        arguments:
            - Litwicki\Bundle\ChargifyBundle\Model\ChargifyEntity
            - "/"
            - "%chargify.domain%"
            - "%chargify.api_id%"
            - "%chargify.api_secret%"
            - "%chargify.api_password%"
            - "%chargify.api_key%"
            - "%chargify.shared_key%"
            - "%chargify.data_format%"
            - "%chargify.test_mode%"
            - "@serializer"

    chargify.handler.adjustment:
        class: Litwicki\Bundle\ChargifyBundle\Handler\Entity\AdjustmentHandler
        arguments:
            - Litwicki\Bundle\ChargifyBundle\Entity\Adjustment
            - "/adjustments"
            - "%chargify.domain%"
            - "%chargify.api_id%"
            - "%chargify.api_secret%"
            - "%chargify.api_password%"
            - "%chargify.api_key%"
            - "%chargify.shared_key%"
            - "%chargify.data_format%"
            - "%chargify.test_mode%"
            - "@serializer"

    chargify.handler.allocation:
        class: Litwicki\Bundle\ChargifyBundle\Handler\Entity\AllocationHandler
        arguments:
            - Litwicki\Bundle\ChargifyBundle\Entity\Allocation
            - "/allocations"
            - "%chargify.domain%"
            - "%chargify.api_id%"
            - "%chargify.api_secret%"
            - "%chargify.api_password%"
            - "%chargify.api_key%"
            - "%chargify.shared_key%"
            - "%chargify.data_format%"
            - "%chargify.test_mode%"
            - "@serializer"

    chargify.handler.charge:
        class: Litwicki\Bundle\ChargifyBundle\Handler\Entity\ChargeHandler
        arguments:
            - Litwicki\Bundle\ChargifyBundle\Entity\Charge
            - "/charges"
            - "%chargify.domain%"
            - "%chargify.api_id%"
            - "%chargify.api_secret%"
            - "%chargify.api_password%"
            - "%chargify.api_key%"
            - "%chargify.shared_key%"
            - "%chargify.data_format%"
            - "%chargify.test_mode%"
            - "@serializer"

    chargify.handler.component:
        class: Litwicki\Bundle\ChargifyBundle\Handler\Entity\ComponentHandler
        arguments:
            - Litwicki\Bundle\ChargifyBundle\Entity\Component
            - "/components"
            - "%chargify.domain%"
            - "%chargify.api_id%"
            - "%chargify.api_secret%"
            - "%chargify.api_password%"
            - "%chargify.api_key%"
            - "%chargify.shared_key%"
            - "%chargify.data_format%"
            - "%chargify.test_mode%"
            - "@serializer"

    chargify.handler.coupon:
        class: Litwicki\Bundle\ChargifyBundle\Handler\Entity\CouponHandler
        arguments:
            - Litwicki\Bundle\ChargifyBundle\Entity\Coupon
            - "/coupons"
            - "%chargify.domain%"
            - "%chargify.api_id%"
            - "%chargify.api_secret%"
            - "%chargify.api_password%"
            - "%chargify.api_key%"
            - "%chargify.shared_key%"
            - "%chargify.data_format%"
            - "%chargify.test_mode%"
            - "@serializer"

    chargify.handler.customer:
        class: Litwicki\Bundle\ChargifyBundle\Handler\Entity\CustomerHandler
        arguments:
            - Litwicki\Bundle\ChargifyBundle\Entity\Customer
            - "/customers"
            - "%chargify.domain%"
            - "%chargify.api_id%"
            - "%chargify.api_secret%"
            - "%chargify.api_password%"
            - "%chargify.api_key%"
            - "%chargify.shared_key%"
            - "%chargify.data_format%"
            - "%chargify.test_mode%"
            - "@serializer"

    chargify.handler.event:
        class: Litwicki\Bundle\ChargifyBundle\Handler\Entity\EventHandler
        arguments:
            - Litwicki\Bundle\ChargifyBundle\Entity\Event
            - "/events"
            - "%chargify.domain%"
            - "%chargify.api_id%"
            - "%chargify.api_secret%"
            - "%chargify.api_password%"
            - "%chargify.api_key%"
            - "%chargify.shared_key%"
            - "%chargify.data_format%"
            - "%chargify.test_mode%"
            - "@serializer"

    chargify.handler.invoice:
        class: Litwicki\Bundle\ChargifyBundle\Handler\Entity\InvoiceHandler
        arguments:
            - Litwicki\Bundle\ChargifyBundle\Entity\Invoice
            - "/invoices"
            - "%chargify.domain%"
            - "%chargify.api_id%"
            - "%chargify.api_secret%"
            - "%chargify.api_password%"
            - "%chargify.api_key%"
            - "%chargify.shared_key%"
            - "%chargify.data_format%"
            - "%chargify.test_mode%"
            - "@serializer"

    chargify.handler.product:
        class: Litwicki\Bundle\ChargifyBundle\Handler\Entity\ProductHandler
        arguments:
            - Litwicki\Bundle\ChargifyBundle\Entity\Product
            - "/products"
            - "%chargify.domain%"
            - "%chargify.api_id%"
            - "%chargify.api_secret%"
            - "%chargify.api_password%"
            - "%chargify.api_key%"
            - "%chargify.shared_key%"
            - "%chargify.data_format%"
            - "%chargify.test_mode%"
            - "@serializer"

    chargify.handler.product_families:
        class: Litwicki\Bundle\ChargifyBundle\Handler\Entity\ProductFamilyHandler
        arguments:
            - Litwicki\Bundle\ChargifyBundle\Entity\ProductFamily
            - "/product_families"
            - "%chargify.domain%"
            - "%chargify.api_id%"
            - "%chargify.api_secret%"
            - "%chargify.api_password%"
            - "%chargify.api_key%"
            - "%chargify.shared_key%"
            - "%chargify.data_format%"
            - "%chargify.test_mode%"
            - "@serializer"

    chargify.handler.subscription:
        class: Litwicki\Bundle\ChargifyBundle\Handler\Entity\SubscriptionHandler
        arguments:
            - Litwicki\Bundle\ChargifyBundle\Entity\Subscription
            - "/subscriptions"
            - "%chargify.domain%"
            - "%chargify.api_id%"
            - "%chargify.api_secret%"
            - "%chargify.api_password%"
            - "%chargify.api_key%"
            - "%chargify.shared_key%"
            - "%chargify.data_format%"
            - "%chargify.test_mode%"
            - "@serializer"

    chargify.handler.transaction:
        class: Litwicki\Bundle\ChargifyBundle\Handler\Entity\TransactionHandler
        arguments:
            - Litwicki\Bundle\ChargifyBundle\Entity\Transaction
            - "/transactions"
            - "%chargify.domain%"
            - "%chargify.api_id%"
            - "%chargify.api_secret%"
            - "%chargify.api_password%"
            - "%chargify.api_key%"
            - "%chargify.shared_key%"
            - "%chargify.data_format%"
            - "%chargify.test_mode%"
            - "@serializer"

    chargify.handler.webhook:
        class: Litwicki\Bundle\ChargifyBundle\Handler\Entity\WebhookHandler
        arguments:
            - Litwicki\Bundle\ChargifyBundle\Entity\Webhook
            - "/webhooks"
            - "%chargify.domain%"
            - "%chargify.api_id%"
            - "%chargify.api_secret%"
            - "%chargify.api_password%"
            - "%chargify.api_key%"
            - "%chargify.shared_key%"
            - "%chargify.data_format%"
            - "%chargify.test_mode%"
            - "@serializer"