services:

    chargify.handler:
        class: Litwicki\Bundle\ChargifyBundle\Services\ChargifyHandler
        arguments: ["%chargify.domain%","%chargify.api_id%","%chargify.api_secret%","%chargify.api_password%","%chargify.api_key%","%chargify.shared_key%","%chargify.data_format%","%chargify.test_mode%"]

    chargify.handler.adjustment:
        class: Litwicki\Bundle\ChargifyBundle\Handler\AdjustmentHandler
        arguments: ["%chargify.domain%","%chargify.api_id%","%chargify.api_secret%","%chargify.api_password%","%chargify.api_key%","%chargify.shared_key%","%chargify.data_format%","%chargify.test_mode%"]

    chargify.handler.customer:
        class: Litwicki\Bundle\ChargifyBundle\Handler\CustomerHandler
        arguments: ["%chargify.domain%","%chargify.api_id%","%chargify.api_secret%","%chargify.api_password%","%chargify.api_key%","%chargify.shared_key%","%chargify.data_format%","%chargify.test_mode%"]
